### ISSUE TITLE
iptables module needs to support multiple chains by same name

### ISSUE THREAD

**Issue by jpds** [puppet-community/puppet-collectd#237]
I would like to be able to do:

    class { 'collectd::plugin::iptables':
      chains  => {
        'filter' => 'INPUT',
        'filter' => 'OUTPUT',
      },
    }

In my config, but it only writes the OUTPUT(/last) option.

**Comment by txaj** [comment]
when I read the manifests I'd guess this should be already the case. can someone reproduce this ?

**Comment by jonnangle** [comment]
I see this problem too; `chains` is a hash and so the keys collide if you try to use this syntax.

An alternative would be:

```puppet
class { 'collectd::plugin::iptables':
  chains  => {
    'filter' => ['INPUT','OUTPUT'],
  },
}
```
I've created a PR #302 which implements this.
