### ISSUE TITLE
use own plugin

### ISSUE THREAD

**Issue by SydOps** [puppet-community/puppet-collectd#354]
May I know how to use own plugin with this forge module?

**Comment by igalic** [comment]
@SydOps there's a [`collectd::plugin`](https://github.com/puppet-community/puppet-collectd#simple-plugins) define, which you can use for simple plugins that don't need any additional configuration.

**Comment by SydOps** [comment]
Thanks, @igalic .

If my plugin is not in the list of exist `collectd::plugin::XXXX` , what can I do? 

I have a python plugin which is downloaded from internet and not in the list.

**Comment by Project0** [comment]
I thought collectd::plugin::python is for python plugins..

**Comment by SydOps** [comment]
@Project0 

Thanks a lot. Will have a try.
