### ISSUE TITLE
MySQL master/slave stats

### ISSUE THREAD

**Issue by mookie-** [puppet-community/puppet-collectd#355]
Hey,

I think you should remove this code from `manifests/plugin/mysql/database.pp`:

```
  if ($masterstats == true and $slavestats == true) {
    fail('master and slave statistics are mutually exclusive.')
  }
```

MySQL supports Master/Master replication where each Master is also a slave and you probably want both. It's possible with the collectd plugin so I don't think you should disable this here.

**Comment by igalic** [comment]
fixed in #365 by @blacktoko
